import type { ManualLocale } from "@/lib/manualLanguage";

type SiteCopy = {
  language: string;
  nav: { calculator: string; annual: string; method: string };
  localStatus: string;
  hero: { kicker: string; titleBefore: string; titleAccent: string; body: string; notes: [string, string, string]; caption: string; captionHint: string };
  form: { kicker: string; title: string; body: string; datetime: string; longitude: string; latitude: string; longitudeHint: string; latitudeHint: string; precision: string; correction: string; gender: string; male: string; female: string; calculate: string; example: string; privacy: string; error: string };
  result: { kicker: string; title: string; subtitle: string; correction: string; correctedSolarTime: string; originalTime: string; chartTime: string; coordinates: string; rule: string; exportKicker: string; exportBody: string; download: string; generating: string; copy: string; copying: string; copied: string; jieQi: string; previous: string; next: string; additional: string; fetalOrigin: string; lifePalace: string; bodyPalace: string; direction: string; fortuneDirection: string; fortuneHint: string; start: string; year: string; localPillars: Record<string, string>; stemDeity: string; hiddenStems: string; naYinState: string; dayMaster: string };
  method: { kicker: string; titleBefore: string; titleAccent: string; firstTitle: string; firstBody: string; secondTitle: string; secondBody: string; thirdTitle: string; thirdBody: string; link: string };
  footer: { brand: string; disclaimer: string };
  city: { label: string; ready: string; connecting: string; placeholder: string; clear: string; searching: string; results: string; selected: string };
};

export const siteCopy: Record<ManualLocale, SiteCopy> = {
  "zh-CN": {
    language: "语言", nav: { calculator: "起盘", annual: "年卷", method: "依据" }, localStatus: "浏览器本地推算",
    hero: { kicker: "观测 / 01", titleBefore: "让出生时刻\n回到它的", titleAccent: "天文位置", body: "以节气为月界，以立春为岁首；将出生地经度折算为真太阳时后，输出可核对的四柱与基础历法信息。", notes: ["节气分界", "标准经线", "晚子时换日"], caption: "历法工作台", captionHint: "请先核对时间与经纬度" },
    form: { kicker: "输入侧注", title: "校对出生条件", body: "请填写按北京时间记录的公历时刻。经度仅作此版本的地方时差修正。", datetime: "公历出生日期与时间", longitude: "出生地经度", latitude: "出生地纬度", longitudeHint: "经度（°，东为正）", latitudeHint: "纬度（°，北为正）", precision: "支持任意有效小数精度；计算不会按 4 位小数截断。", correction: "地方时差", gender: "性别（用于大运方向）", male: "男", female: "女", calculate: "推算四柱", example: "恢复示例：1990.01.27 北京", privacy: "本工具不保存输入信息；结果仅供历法与文化研究参考。", error: "无法完成本次推算，请核对输入。" },
    result: { kicker: "四柱版心", title: "乾支排布", subtitle: "八字", correction: "经度校正", correctedSolarTime: "真太阳时", originalTime: "原始北京时间", chartTime: "用于排盘的时刻", coordinates: "经度 {longitude}° · 纬度 {latitude}°", rule: "排盘规则：已采用晚子时（23:00 起）换日规则。年、月柱由内置历法的节气时刻界定；月柱按节而非农历月切换。", exportKicker: "导出 / 03", exportBody: "导出仅在当前浏览器本地生成，不会上传出生信息。", download: "下载 PNG 排盘卡", generating: "正在生成", copy: "复制纯文本", copying: "正在复制", copied: "纯文本排盘已复制到剪贴板。", jieQi: "节气校验", previous: "前一节", next: "后一节", additional: "附加信息", fetalOrigin: "胎元", lifePalace: "命宫", bodyPalace: "身宫", direction: "大运方向", fortuneDirection: "大运序列", fortuneHint: "按性别与年干阴阳推演", start: "起", year: "岁", localPillars: { year: "年柱", month: "月柱", day: "日柱", hour: "时柱" }, stemDeity: "天干十神", hiddenStems: "地支藏干", naYinState: "纳音 / 地势", dayMaster: "日主" },
    method: { kicker: "计算依据 / 05", titleBefore: "不是“农历生日”，\n而是", titleAccent: "时刻与节气", firstTitle: "真太阳时修正", firstBody: "以 120°E 为基准，按经度差每度 4 分钟折算地方时差。", secondTitle: "立春与节令", secondBody: "年柱以立春为分界；月柱随十二节转换，而非随农历初一转换。", thirdTitle: "晚子时处理", thirdBody: "当前版本以 23:00 作为换日边界；流派差异应在正式使用前另行核对。", link: "查看所用历法库说明" },
    footer: { brand: "观历 · 一个可核对的四柱排盘界面", disclaimer: "资料性工具，不构成命理解读、医疗、法律、投资或人生决策建议。" },
    city: { label: "出生城市", ready: "地点服务已就绪", connecting: "正在连接地点服务", placeholder: "输入城市，如北京、上海", clear: "清除城市", searching: "正在搜索", results: "城市搜索结果", selected: "已选" },
  },
  "zh-TW": {
    language: "語言", nav: { calculator: "起盤", annual: "年卷", method: "依據" }, localStatus: "瀏覽器本機推算",
    hero: { kicker: "觀測 / 01", titleBefore: "讓出生時刻\n回到它的", titleAccent: "天文位置", body: "以節氣為月界，以立春為歲首；將出生地經度折算為真太陽時後，輸出可核對的四柱與基礎曆法資訊。", notes: ["節氣分界", "標準經線", "晚子時換日"], caption: "曆法工作臺", captionHint: "請先核對時間與經緯度" },
    form: { kicker: "輸入側註", title: "校對出生條件", body: "請填寫按北京時間記錄的公曆時刻。經度僅作此版本的地方時差修正。", datetime: "公曆出生日期與時間", longitude: "出生地經度", latitude: "出生地緯度", longitudeHint: "經度（°，東為正）", latitudeHint: "緯度（°，北為正）", precision: "支援任意有效小數精度；計算不會按 4 位小數截斷。", correction: "地方時差", gender: "性別（用於大運方向）", male: "男", female: "女", calculate: "推算四柱", example: "恢復範例：1990.01.27 北京", privacy: "本工具不保存輸入資料；結果僅供曆法與文化研究參考。", error: "無法完成本次推算，請核對輸入。" },
    result: { kicker: "四柱版心", title: "干支排布", subtitle: "八字", correction: "經度校正", correctedSolarTime: "真太陽時", originalTime: "原始北京時間", chartTime: "用於排盤的時刻", coordinates: "經度 {longitude}° · 緯度 {latitude}°", rule: "排盤規則：已採用晚子時（23:00 起）換日規則。年、月柱由內建曆法的節氣時刻界定；月柱按節而非農曆月切換。", exportKicker: "匯出 / 03", exportBody: "匯出僅在目前瀏覽器本機生成，不會上傳出生資料。", download: "下載 PNG 排盤卡", generating: "正在生成", copy: "複製純文字", copying: "正在複製", copied: "純文字排盤已複製到剪貼簿。", jieQi: "節氣校驗", previous: "前一節", next: "後一節", additional: "附加資訊", fetalOrigin: "胎元", lifePalace: "命宮", bodyPalace: "身宮", direction: "大運方向", fortuneDirection: "大運序列", fortuneHint: "按性別與年干陰陽推演", start: "起", year: "歲", localPillars: { year: "年柱", month: "月柱", day: "日柱", hour: "時柱" }, stemDeity: "天干十神", hiddenStems: "地支藏干", naYinState: "納音 / 地勢", dayMaster: "日主" },
    method: { kicker: "計算依據 / 05", titleBefore: "不是「農曆生日」，\n而是", titleAccent: "時刻與節氣", firstTitle: "真太陽時修正", firstBody: "以 120°E 為基準，按經度差每度 4 分鐘折算地方時差。", secondTitle: "立春與節令", secondBody: "年柱以立春為分界；月柱隨十二節轉換，而非隨農曆初一轉換。", thirdTitle: "晚子時處理", thirdBody: "目前版本以 23:00 作為換日邊界；流派差異應在正式使用前另行核對。", link: "查看所用曆法庫說明" },
    footer: { brand: "觀曆 · 一個可核對的四柱排盤介面", disclaimer: "資料性工具，不構成命理解讀、醫療、法律、投資或人生決策建議。" },
    city: { label: "出生城市", ready: "地點服務已就緒", connecting: "正在連線地點服務", placeholder: "輸入城市，如北京、上海", clear: "清除城市", searching: "正在搜尋", results: "城市搜尋結果", selected: "已選" },
  },
  en: {
    language: "Language", nav: { calculator: "Chart", annual: "Annual", method: "Method" }, localStatus: "Calculated locally in this browser",
    hero: { kicker: "OBSERVATION / 01", titleBefore: "Return the birth\nmoment to its", titleAccent: "astronomical place", body: "Use solar terms as month boundaries and Li Chun as the year boundary. Birth longitude is converted to local solar time for a checkable Four Pillars chart.", notes: ["solar-term boundaries", "120°E reference meridian", "23:00 late-Zi day boundary"], caption: "Calendar workbench", captionHint: "Verify time and coordinates first" },
    form: { kicker: "INPUT NOTES", title: "Check birth details", body: "Enter the Gregorian time as recorded in Beijing time. Longitude is used only for this version's local-time correction.", datetime: "Gregorian birth date and time", longitude: "Birth longitude", latitude: "Birth latitude", longitudeHint: "Longitude (°, east positive)", latitudeHint: "Latitude (°, north positive)", precision: "Any valid decimal precision is accepted; calculations are not truncated to four decimal places.", correction: "Local-time correction", gender: "Gender (for the fortune-cycle direction)", male: "Male", female: "Female", calculate: "Calculate Four Pillars", example: "Restore example: Beijing, 1990-01-27", privacy: "This tool does not save input details; output is for calendar and cultural research only.", error: "The chart could not be calculated. Please check the details." },
    result: { kicker: "FOUR-PILLAR CORE", title: "Pillar layout", subtitle: "BĀZÌ", correction: "Longitude correction", correctedSolarTime: "Local solar time", originalTime: "Original Beijing time", chartTime: "Time used for charting", coordinates: "Longitude {longitude}° · Latitude {latitude}°", rule: "Charting rule: the late-Zi (23:00 onward) day-boundary convention is used. Year and month pillars follow solar-term instants; the month pillar does not change at lunar-month starts.", exportKicker: "EXPORT / 03", exportBody: "Exports are created locally in this browser; birth details are not uploaded.", download: "Download PNG chart", generating: "Generating", copy: "Copy plain text", copying: "Copying", copied: "Plain-text chart copied to the clipboard.", jieQi: "Solar-term check", previous: "Previous", next: "Next", additional: "Additional details", fetalOrigin: "Fetal origin", lifePalace: "Life palace", bodyPalace: "Body palace", direction: "Fortune-cycle direction", fortuneDirection: "Fortune-cycle sequence", fortuneHint: "Derived from gender and the year stem's yin–yang property", start: "from", year: "years", localPillars: { year: "Year pillar", month: "Month pillar", day: "Day pillar", hour: "Hour pillar" }, stemDeity: "Stem relation", hiddenStems: "Hidden stems", naYinState: "Na Yin / phase", dayMaster: "Day master" },
    method: { kicker: "METHOD / 05", titleBefore: "Not a lunar birthday,\nbut", titleAccent: "time and solar terms", firstTitle: "Local solar-time correction", firstBody: "Using 120°E as the reference, local-time correction is four minutes per degree of longitude difference.", secondTitle: "Li Chun and solar terms", secondBody: "The year pillar changes at Li Chun; the month pillar changes at the twelve solar terms, not on the first day of a lunar month.", thirdTitle: "Late-Zi convention", thirdBody: "This version uses 23:00 as the day boundary; differences among traditions should be checked before formal use.", link: "View the calendar library" },
    footer: { brand: "Guanli · A checkable Four Pillars interface", disclaimer: "An informational tool, not divination, medical, legal, investment, or life-decision advice." },
    city: { label: "Birth city", ready: "Place service ready", connecting: "Connecting to place service", placeholder: "Search a city, e.g. Beijing or Shanghai", clear: "Clear city", searching: "Searching", results: "City search results", selected: "Selected" },
  },
};
